language:
 - php
php:
 - 5.5
 
before_install:
# Install Testspace Runner
 - ./testspace_install.sh
 - export PATH="${HOME}/testspace:${PATH}" 
 
script:
 - composer install
 - vendor/bin/phpunit tests/unit --log-junit tests-results.xml --coverage-clover coverage.xml
 
# Publish Test Results along with Coverage
 - testspace publish [Tests]tests-results.xml{tests/unit} coverage.xml ${TESTSPACE_URL}