language:
 - php
 
php:
 - 5.5
 
before_script:
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url samples.testspace.com
  - composer install
   
script:
  - vendor/bin/phpcs src tests --report-gitblame=analysis-sniffer-blame.txt --report-checkstyle=analysis-sniffer.xml || true
  - vendor/bin/phpmd src,tests xml codesize,naming,unusedcode --reportfile analysis-mess.xml || true
  - vendor/bin/phpunit tests/unit --log-junit tests-results.xml --coverage-clover coverage.xml

# refer to ".testspace.txt" for list of content
after_script:
  - testspace @.testspace.txt