language:
 - php
php:
 - 5.5
 
before_install:
# Install Testspace Runner
 - ./testspace_install.sh
 
script:
 - composer install
 - vendor/bin/phpunit tests/unit --log-junit tests-results.xml --coverage-clover coverage.xml
 
# Publish Test Results along with Coverage
 - export PATH="${HOME}/testspace:${PATH}"
# Testspace credentials: "credentials@myorg.testspace.com/myproject/myspace
 - testspace config url ${TESTSPACE_USER_TOKEN}:@${TESTSPACE_URL}
 - testspace publish [Tests]tests-results.xml{tests/unit} coverage.xml