version: 2
jobs:
  build:
    docker:
      - image: circleci/php:5.6.37-cli-node-browsers
    steps:
      - checkout
      - run:
          name: Get latest testspace client
          command: curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | sudo tar -zxvf- -C /usr/local/bin
      - run:
          name: Configure testspace client
          command: testspace config url samples.testspace.com
      - run: composer install
      - run: vendor/bin/phpcs src tests --report-gitblame=analysis-sniffer-blame.txt --report-checkstyle=analysis-sniffer.xml || true
      - run: vendor/bin/phpmd src,tests xml codesize,naming,unusedcode --reportfile analysis-mess.xml || true 
      - run: vendor/bin/phpunit tests/unit --log-junit tests-results.xml --coverage-clover coverage.xml
      - run:
          name: Send reports to testspace
          command: testspace @.testspace.txt
          when: always
