name: Build
on:
  push:
  schedule:
    - cron:  '0 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 5.6
          extensions: sqlite
          tools: composer, phpcs, phpmd, phpunit
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: samples
      - name: Install
        run: |
          composer install
      - name: Analyze
        run: |
          vendor/bin/phpcs src tests --report-gitblame=analysis-sniffer-blame.txt --report-checkstyle=analysis-sniffer.xml || true
          vendor/bin/phpmd src,tests xml codesize,naming,unusedcode --reportfile analysis-mess.xml || true
      - name: Test
        run: |
          vendor/bin/phpunit tests/unit --log-junit tests-results.xml --coverage-clover coverage.xml
      - name: Push
        run: |
          testspace @.testspace.txt
        if: always()
